# Generated by Django 3.2.7 on 2021-10-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('Amazon_SKU', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Amazon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amazon_Ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Amazon_Reviews', models.IntegerField()),
                ('Amazon_Status', models.CharField(max_length=32)),
                ('Amazon_URL', models.CharField(max_length=256)),
                ('Amazon_UUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.products')),
            ],
        ),
    ]
