# Generated by Django 3.2.7 on 2021-10-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('MicroCenter_SKU', models.IntegerField()),
                ('BestBuy_SKU', models.IntegerField()),
            ],
        ),
    ]
