# Generated by Django 3.2.7 on 2021-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroCenter',
            fields=[
                ('MicroCenter_Name', models.CharField(max_length=256)),
                ('MicroCenter_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MicroCenter_SKU', models.IntegerField(primary_key=True, serialize=False)),
                ('MicroCenter_ModelNumber', models.CharField(max_length=128)),
                ('MicroCenter_URL', models.CharField(max_length=256)),
            ],
        ),
    ]
