# Generated by Django 3.2.7 on 2021-10-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('AD_SKU', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('AD_Name', models.CharField(max_length=256)),
                ('AD_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AD_Status', models.CharField(max_length=32)),
                ('AD_URL', models.CharField(max_length=256)),
                ('AD_UUID', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BH',
            fields=[
                ('BH_SKU', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('BH_Name', models.CharField(max_length=256)),
                ('BH_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BH_Status', models.CharField(max_length=32)),
                ('BH_URL', models.CharField(max_length=256)),
                ('BH_UUID', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Gamestop',
            fields=[
                ('Gamestop_SKU', models.IntegerField(primary_key=True, serialize=False)),
                ('Gamestop_Name', models.CharField(max_length=256)),
                ('Gamestop_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Gamestop_URL', models.CharField(max_length=256)),
                ('Gamestop_Status', models.CharField(max_length=32)),
                ('Gamestop_UUID', models.CharField(max_length=128)),
            ],
        ),
    ]
