# Generated by Django 3.2.7 on 2021-11-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='AD_Reviews',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='Amazon_Reviews',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bestbuy',
            name='BestBuy_Review',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bh',
            name='BH_Reviews',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gamestop',
            name='Gamestop_Reviews',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
