# Generated by Django 3.2.7 on 2021-10-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestbuy',
            name='id',
        ),
        migrations.AlterField(
            model_name='bestbuy',
            name='SKU',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
