# Generated by Django 3.2.7 on 2021-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_amazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='Amazon_Status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='Amazon_URL',
            field=models.CharField(max_length=512),
        ),
    ]
